=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/export.dtd
<!ELEMENT Export (Sizes?, settings, activateDICs?)>
<!ATTLIST Export
	from CDATA #REQUIRED
	to CDATA #REQUIRED>
	
<!ELEMENT Sizes ((sizeFromFileLength | sizeFromFileLine | sizeInBits)+)>

<!ELEMENT sizeFromFileLength EMPTY>
<!ATTLIST sizeFromFileLength
	id CDATA #REQUIRED
	fromFile CDATA #REQUIRED
	addSize CDATA #IMPLIED
	unit (bits | bytes) #IMPLIED>

<!ELEMENT sizeFromFileLine EMPTY>
<!ATTLIST sizeFromFileLine
	id CDATA #REQUIRED
	fromFile CDATA #REQUIRED
	line CDATA #REQUIRED
	addSize CDATA #IMPLIED
	unit (bits | bytes) #IMPLIED>

<!ELEMENT sizeInBits EMPTY>
<!ATTLIST sizeInBits
	id CDATA #REQUIRED
	from CDATA #REQUIRED
	addSize CDATA #IMPLIED
	unit (bits | bytes) #IMPLIED>

<!ELEMENT settings ((settingFromConst | settingFromSize | settingFromFile | settingFromField | settingAIFromConst | settingAIFromFile)*)>

<!ELEMENT settingFromConst EMPTY>
<!ATTLIST settingFromConst
	value CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED>
	
<!ELEMENT settingFromSize EMPTY>
<!ATTLIST settingFromSize
	sizeRef CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED>
	
<!ELEMENT settingFromFile EMPTY>
<!ATTLIST settingFromFile
	file CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED
	offset CDATA #IMPLIED
	size CDATA #IMPLIED
	line CDATA #IMPLIED>
	
<!ELEMENT settingFromField EMPTY>
<!ATTLIST settingFromField
	fieldRef CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED>

<!ELEMENT settingAIFromConst EMPTY>
<!ATTLIST settingAIFromConst
	value CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED
	toArrayIndex CDATA #REQUIRED>
	
<!ELEMENT settingAIFromFile EMPTY>
<!ATTLIST settingAIFromFile
	file CDATA #REQUIRED
	toFieldRef CDATA #REQUIRED
	toArrayIndex CDATA #REQUIRED
	offset CDATA #IMPLIED
	size CDATA #IMPLIED
	line CDATA #IMPLIED>
	
<!ELEMENT activateDICs (DIC+)>

<!ELEMENT DIC EMPTY>
<!ATTLIST DIC
	id CDATA #REQUIRED
	DICRef CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Lv2_To_Lv1/st03/asw_pus_tc_3_6_to_asw_pus_v2_tc_ack.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Export SYSTEM "../../../DTDs/export.dtd">

<Export from="../Level2/st03/asw_pus_tc_3_31_format.xml" to="../Level1/asw_pus_v2_tc_format.xml">
	<settings>
		<settingFromConst value="0" toFieldRef="CCSDSSecondaryHeaderFlag"/>
		<settingFromConst value="1" toFieldRef="PUSVersion"/>
		<settingFromConst value="11" toFieldRef="ACK"/>
		<settingFromConst value="3" toFieldRef="ServiceType"/>
		<settingFromConst value="6" toFieldRef="ServiceSubtype"/>
		<settingFromConst value="120" toFieldRef="SourceID"/>
		<settingFromField fieldRef="ApplicationData" toFieldRef="ApplicationData"/>
		<settingFromConst value="3" toFieldRef="AppDataLength"/> <!-- Virtual, 1 bytes of EPD PUS TC 3.31 AppData -->
	</settings>
</Export>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Lv2_To_Lv1/st06/asw_pus_tc_6_2_to_asw_pus_v2_tc_ack_0b1001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Export SYSTEM "../../../DTDs/export.dtd">

<Export from="../Level2/st02/asw_pus_tc_2_1_format.xml" to="../Level1/asw_pus_v2_tc_format.xml">
	<Sizes>
		<sizeInBits id="0" from="DataToWrite" addSize="8" unit="bytes"/>
	</Sizes>

	<settings>
		<settingFromConst value="0" toFieldRef="CCSDSSecondaryHeaderFlag"/>
		<settingFromConst value="1" toFieldRef="PUSVersion"/>
		<settingFromConst value="9" toFieldRef="ACK"/>
		<settingFromConst value="6" toFieldRef="ServiceType"/>
		<settingFromConst value="2" toFieldRef="ServiceSubtype"/>
		<settingFromConst value="120" toFieldRef="SourceID"/>
		<settingFromField fieldRef="ApplicationData" toFieldRef="ApplicationData"/>
		<settingFromSize sizeRef="0" toFieldRef="AppDataLength"/>
	</settings>
</Export>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/STEPS_XML/INPUTS/tc_6_2/tc_6_2_write_bytes_to_read_only_memory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Export SYSTEM "../../DTDs/export.dtd">
<Export from="NULL" to="asw_pus_6_2.xml">

	<Sizes>
		<sizeFromFileLength id="0" fromFile="STEPS_XML/INPUTS/tc_6_2/bytes_to_write.txt"/>
	</Sizes>

	<settings>
		<settingFromConst value="0" toFieldRef="MemoryID"/>
		<settingFromConst value="1" toFieldRef="N"/>
		<settingFromConst value="0x100" toFieldRef="StartAddress"/>
		<settingFromSize sizeRef="0" toFieldRef="Length"/>
		<settingFromFile file="STEPS_XML/INPUTS/tc_6_2/bytes_to_write.txt" toFieldRef="DataToWrite"/>
	</settings>
</Export>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/STEPS_XML/INPUTS/tc_12_05/tc_12_5_set_pmonid_0_to_pid10_to_0x01_0x4000_0x0A_0x4001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Export SYSTEM "../../DTDs/export.dtd">
<Export from="NULL" to="epd_pus_12_5.xml">
	<settings>
		<settingFromConst value="1" toFieldRef="N"/>
		<settingFromConst value="0" toFieldRef="PMON_ID"/>
		<settingFromConst value="10" toFieldRef="Parameter_ID"/>
		<settingFromConst value="8" toFieldRef="Monitoring_Interval"/>
		<settingFromConst value="2" toFieldRef="Repetition"/>
		<settingFromConst value="1" toFieldRef="Type"/>				
		<settingFromConst value="1" toFieldRef="Low_Limit"/>
		<settingFromConst value="0x4000" toFieldRef="Low_Limit_EV_ID"/>
		<settingFromConst value="10" toFieldRef="High_Limit"/>
		<settingFromConst value="0x4001" toFieldRef="High_Limit_EV_ID"/>
	</settings>
</Export>
