=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/filters.dtd
<!ELEMENT MaxtermFilter ((BoolVar | BoolVarFromArrayItem | BoolVarFromGroupedArrayItem | BoolVarFDIC)+, Maxterm+)>
<!ATTLIST MaxtermFilter
	formatFile CDATA #REQUIRED>

<!ELEMENT MintermFilter ((BoolVar | BoolVarFromArrayItem | BoolVarFromGroupedArrayItem | BoolVarFDIC)+, Minterm+)>
<!ATTLIST MintermFilter
	formatFile CDATA #REQUIRED>

<!ELEMENT BoolVar (FieldRef, Op, (Constant | Select | SelectLine))>
<!ATTLIST BoolVar
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	constantType (decimal | hex | binary | char | string) #REQUIRED>

<!ELEMENT FieldRef EMPTY>
<!ATTLIST FieldRef
	name CDATA #REQUIRED>

<!ELEMENT Op EMPTY>
<!ATTLIST Op
	type (equal | different | bigger_than | smaller_than | bigger_or_equal | smaller_or_equal ) #REQUIRED>

<!ELEMENT Constant EMPTY>
<!ATTLIST Constant
	value CDATA #REQUIRED
	mask CDATA #IMPLIED>

<!ELEMENT Select EMPTY>
<!ATTLIST Select
	fromFile CDATA #REQUIRED
	type (data | size | crc) #REQUIRED
	offset CDATA #IMPLIED
	size CDATA #IMPLIED
	mask CDATA #IMPLIED>

<!ELEMENT SelectLine EMPTY>
<!ATTLIST SelectLine
	fromFile CDATA #REQUIRED
	line CDATA #REQUIRED
	leftTrim CDATA #IMPLIED
	rightTrim CDATA #IMPLIED
	mask CDATA #IMPLIED>

<!ELEMENT BoolVarFDIC (FieldRef, Op)>
<!ATTLIST BoolVarFDIC
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED>

<!ELEMENT Maxterm (BoolVarRef+)>
<!ATTLIST Maxterm
	id NMTOKEN #REQUIRED>

<!ELEMENT Minterm (BoolVarRef+)>
<!ATTLIST Minterm
	id NMTOKEN #REQUIRED>

<!ELEMENT BoolVarRef EMPTY>
<!ATTLIST BoolVarRef
	idRef NMTOKEN #REQUIRED>

<!ELEMENT BoolVarFromArrayItem (AIFieldRef, Op, (Constant | Select | SelectLine))>
<!ATTLIST BoolVarFromArrayItem
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	constantType (decimal | hex | binary | char | string) #REQUIRED>

<!ELEMENT AIFieldRef EMPTY>
<!ATTLIST AIFieldRef
	name CDATA #REQUIRED
	index CDATA #REQUIRED>

<!ELEMENT BoolVarFromGroupedArrayItem (AIFieldRefs, Op, (Constant | Select | SelectLine))>
<!ATTLIST BoolVarFromGroupedArrayItem
	id NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	constantType (decimal | hex | binary | char | string) #REQUIRED
	group CDATA #REQUIRED>

<!ELEMENT AIFieldRefs EMPTY>
<!ATTLIST AIFieldRefs
	name CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level1/Extra/epd_pus_tm_1_7_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level1/epd_pus_tm_format.xml">
	<BoolVar id="0" name="ServiceType1" constantType="decimal">
		<FieldRef name="ServiceType" />
		<Op type="equal" />
		<Constant value="1" />
	</BoolVar>
	<BoolVar id="1" name="ServiceSubtype2" constantType="decimal">
		<FieldRef name="ServiceSubtype" />
		<Op type="equal" />
		<Constant value="7" />
	</BoolVar>

	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level2/st06/asw_pus_tm_6_6_read_from_0x41020080_to_0x41020097_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level2/st06/asw_pus_tm_6_6_format.xml">
    <BoolVar id="0" name="memory_id_equal_to_1" constantType="hex">
		<FieldRef name="MemoryID" />
		<Op type="equal" />
		<Constant value="1" />
	</BoolVar>
	<BoolVar id="1" name="N_equal_to_1" constantType="hex">
		<FieldRef name="N" />
		<Op type="equal" />
		<Constant value="0x1" />
	</BoolVar>
	<BoolVar id="2" name="StartAddess_equal_to_0x1080" constantType="hex">
		<FieldRef name="StartAddress" />
		<Op type="equal" />
		<Constant value="20080" />
	</BoolVar>
	<BoolVar id="3" name="Length_equal_to_24" constantType="decimal">
		<FieldRef name="Length" />
		<Op type="equal" />
		<Constant value="24" />
	</BoolVar>
	<BoolVar id="4" name="ReadDataEqual" constantType="string">
		<FieldRef name="ReadData" />
		<Op type="equal" />
		<Select fromFile="TM_Filters/Level2/st06/read_bytes_from_0x41020080_to_0x41020097.txt" type="data" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
		<BoolVarRef idRef="2" />
		<BoolVarRef idRef="3" />
		<BoolVarRef idRef="4" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level2/st12/asw_pus_tm_12_12_limits_monitoring_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level2/asw_pus_tm_12_12_limits_monitoring_format.xml">
    <BoolVar id="0" name="counter_equal_to_1" constantType="hex">
		<FieldRef name="counter" />
		<Op type="equal" />
		<Constant value="Ox1" />
	</BoolVar>
	<BoolVar id="1" name="limits_PMON_type" constantType="hex">
		<FieldRef name="PMON_type" />
		<Op type="equal" />
		<Constant value="0x1" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level2/st20/asw_pus_tm_20_2_pid10_uint32_equal_99_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../../TM_Formats/Level2/asw_pus_tm_20_2_uint32_format.xml">
	<BoolVar id="0" name="N0" constantType="decimal">
		<FieldRef name="N" />
		<Op type="equal" />
		<Constant value="1" />
	</BoolVar>
	<BoolVar id="1" name="PID0" constantType="decimal">
		<FieldRef name="PID" />
		<Op type="equal" />
		<Constant value="10" />
	</BoolVar>
	<BoolVar id="2" name="PID0Value" constantType="decimal">
		<FieldRef name="PIDValue" />
		<Op type="equal" />
		<Constant value="99" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
		<BoolVarRef idRef="2" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level0/asw_ccsds_pus_v2_tm_filter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE MintermFilter SYSTEM "../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level0/cssds_pus_v2_tm_format.xml">
	<BoolVar id="0" name="VersionIs2" constantType="decimal">
		<FieldRef name="VersionNumber" />
		<Op type="equal" />
		<Constant value="2" />
	</BoolVar>
	<BoolVar id="1" name="TypeIs0" constantType="decimal">
		<FieldRef name="Type" />
		<Op type="equal" />
		<Constant value="0" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level2/st06/asw_pus_tm_6_10_checksum_from_0x40000090_to_0x400000BF_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level2/st06/asw_pus_tm_6_10_format.xml">
    <BoolVar id="0" name="memory_id_equal_to_0" constantType="hex">
		<FieldRef name="MemoryID" />
		<Op type="equal" />
		<Constant value="0" />
	</BoolVar>
	<BoolVar id="1" name="N_equal_to_1" constantType="hex">
		<FieldRef name="N" />
		<Op type="equal" />
		<Constant value="0x1" />
	</BoolVar>
	<BoolVar id="2" name="StartAddess_equal_to_0x90" constantType="hex">
		<FieldRef name="StartAddress" />
		<Op type="equal" />
		<Constant value="90" />
	</BoolVar>
	<BoolVar id="3" name="Length_equal_to_48" constantType="decimal">
		<FieldRef name="Length" />
		<Op type="equal" />
		<Constant value="48" />
	</BoolVar>
	<BoolVar id="4" name="ChecksumEqual" constantType="hex">
		<FieldRef name="Checksum" />
		<Op type="equal" />
		<Constant value="DD18" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
		<BoolVarRef idRef="2" />
		<BoolVarRef idRef="3" />
		<BoolVarRef idRef="4" />
	</Minterm>
</MintermFilter>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Filters/Level2/st04/asw_pus_tm_4_2_PID_3_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MintermFilter SYSTEM "../../../DTDs/filters.dtd">

<MintermFilter formatFile="../../TM_Formats/Level2/asw_pus_tm_4_2_format.xml">
	<BoolVar id="0" name="N" constantType="hex">
		<FieldRef name="N" />
		<Op type="equal" />
		<Constant value="0x1" />
	</BoolVar>
	<BoolVar id="1" name="PID" constantType="hex">
		<FieldRef name="PID" />
		<Op type="equal" />
		<Constant value="0x3" />
	</BoolVar>
	<Minterm id="0">
		<BoolVarRef idRef="0" />
		<BoolVarRef idRef="1" />
	</Minterm>
</MintermFilter>
