=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/gss_config.dtd
<!ELEMENT gss_config (gss_options, Protocols, Interfaces, SpecialPackets?, PeriodicTCs?, GlobalVars?, Monitors?, Tests)>

<!ELEMENT gss_options (gss_info, gss_info_print, phy_header_print, discardErrorFlags)>
<!ELEMENT Protocols (Protocol+)>
<!ELEMENT Interfaces (MainInterface, (Interface+))>
<!ELEMENT SpecialPackets (SpecialPacket+)>
<!ELEMENT PeriodicTCs ((PeriodicTC_level_2 | PeriodicTC_level_1 | PeriodicTC_level_0)*)>
<!ELEMENT GlobalVars (GlobalVar+)>
<!ELEMENT Monitors ((plot | alarmMsg | modify | alarmVal)*)>
<!ATTLIST Monitors
	ChartsFile CDATA #IMPLIED>
<!ELEMENT Tests (TestCase+)>
<!ATTLIST Tests
	ProtocolPacketsFile CDATA #IMPLIED>

<!ELEMENT gss_info EMPTY>
<!ATTLIST gss_info
	test_campaign CDATA #REQUIRED
	version CDATA #REQUIRED
	date CDATA #REQUIRED
	version_control_url CDATA #IMPLIED>

<!ELEMENT gss_info_print EMPTY>
<!ATTLIST gss_info_print
	mainLog (enabled | disabled) #REQUIRED
	portLogs (enabled | disabled) #REQUIRED
	rawLog (enabled | disabled) #REQUIRED>

<!ELEMENT phy_header_print EMPTY>
<!ATTLIST phy_header_print
	mainLog (enabled | disabled) #REQUIRED
	portLogs (enabled | disabled) #REQUIRED
	rawLog (enabled | disabled) #REQUIRED
	gssTabs (enabled | disabled) #REQUIRED>

<!ELEMENT discardErrorFlags EMPTY>
<!ATTLIST discardErrorFlags
	txErrors (enabled | disabled) #REQUIRED
	notExpectedPackets (enabled | disabled) #REQUIRED
	filtersKo (enabled | disabled) #REQUIRED
	validTimesKo (enabled | disabled) #REQUIRED>
	
<!ELEMENT Protocol EMPTY>
<!ATTLIST Protocol
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	typeLevel CDATA #REQUIRED
	typeOffset CDATA #REQUIRED
	subtypeOffset CDATA #IMPLIED>

<!ELEMENT MainInterface ((LevelInOut | LevelIn | LevelOut)+)>
<!ATTLIST MainInterface
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	ifType (SpW | uart | dummy) #REQUIRED
	ifConfig CDATA #REQUIRED
	ioType (in_out) #REQUIRED
	protocolID CDATA #IMPLIED>

<!ELEMENT Interface ((LevelInOut | LevelIn | LevelOut)+)>
<!ATTLIST Interface
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	ifType (SpW | SpW_TC | SpW_Error | uart | dummy) #REQUIRED
	ifConfig CDATA #REQUIRED
	ioType (in | out | in_out) #REQUIRED
	protocolID CDATA #IMPLIED>

<!ELEMENT LevelInOut (TMformat, TCformat, inputFilter, export_to_prev_Level?, import_from_prev_Level?)>
<!ATTLIST LevelInOut
	id CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT LevelIn (TCformat, export_to_prev_Level?)>
<!ATTLIST LevelIn
	id CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT LevelOut (TMformat, inputFilter, import_from_prev_Level?)>
<!ATTLIST LevelOut
	id CDATA #REQUIRED
	name CDATA #REQUIRED>

<!ELEMENT TMformat EMPTY>
<!ATTLIST TMformat
	file CDATA #REQUIRED>
<!ELEMENT TCformat EMPTY>
<!ATTLIST TCformat
	file CDATA #REQUIRED>
<!ELEMENT inputFilter EMPTY>
<!ATTLIST inputFilter 
	file CDATA #REQUIRED>
<!ELEMENT export_to_prev_Level EMPTY>
<!ATTLIST export_to_prev_Level 
	file CDATA #REQUIRED>
<!ELEMENT import_from_prev_Level EMPTY>
<!ATTLIST import_from_prev_Level 
	file CDATA #REQUIRED>

<!ELEMENT SpecialPacket (inputFilter, UpperLevels?, printingData, (period | intervalRange)?)>
<!ATTLIST SpecialPacket
	status (enabled | disabled) #REQUIRED
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	levels CDATA #REQUIRED
	levelRef CDATA #REQUIRED>
<!ELEMENT UpperLevels (UpperLevel+)>
<!ELEMENT UpperLevel (TMformat, inputFilter, import_from_prev_Level)>
<!ATTLIST UpperLevel
	level (1 | 2 | 3) #REQUIRED>
<!ELEMENT printingData (structuredData?)>
<!ATTLIST printingData
	printStatus (enabled | disabled) #REQUIRED>
<!ELEMENT structuredData EMPTY>
<!ATTLIST structuredData
	levelRef CDATA #REQUIRED
	firstField CDATA #REQUIRED>
<!ELEMENT period EMPTY>
<!ATTLIST period
	min_value CDATA #REQUIRED
	min_unit (miliseconds | seconds) #REQUIRED
	max_value CDATA #REQUIRED
	max_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT intervalRange EMPTY>
<!ATTLIST intervalRange
	min CDATA #REQUIRED
	max CDATA #REQUIRED
	interval_value CDATA #REQUIRED
	interval_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT PeriodicTC_level_2 (level2, app_to_level2, level1, level2_to_level1, level0, level1_to_level0)>
<!ATTLIST PeriodicTC_level_2
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	period_value CDATA #REQUIRED
	period_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT PeriodicTC_level_1 (level1, app_to_level1, level0, level1_to_level0)>
<!ATTLIST PeriodicTC_level_1
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	period_value CDATA #REQUIRED
	period_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT PeriodicTC_level_0 (level0, app_to_level0)>
<!ATTLIST PeriodicTC_level_0
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	period_value CDATA #REQUIRED
	period_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT level2 EMPTY>
<!ATTLIST level2
	format CDATA #REQUIRED>
<!ELEMENT level1 EMPTY>
<!ATTLIST level1
	format CDATA #REQUIRED>
<!ELEMENT level0 EMPTY>
<!ATTLIST level0
	format CDATA #REQUIRED>

<!ELEMENT app_to_level2 EMPTY>
<!ATTLIST app_to_level2 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level1 EMPTY>
<!ATTLIST app_to_level1 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level0 EMPTY>
<!ATTLIST app_to_level0 
	export CDATA #REQUIRED>

<!ELEMENT level2_to_level1 EMPTY>
<!ATTLIST level2_to_level1
	export CDATA #REQUIRED>
<!ELEMENT level1_to_level0 EMPTY>
<!ATTLIST level1_to_level0
	export CDATA #REQUIRED>

<!ELEMENT GlobalVar (referenceField | referencePeriodicTC | referenceSpecialPacket)>
<!ATTLIST GlobalVar
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	type (uint | formula) #REQUIRED
	initial_value CDATA #REQUIRED>
<!ELEMENT referenceField EMPTY>
<!ATTLIST referenceField
	type (tm | tc) #REQUIRED
	ifRef CDATA #REQUIRED
	level CDATA #REQUIRED
	fieldRef CDATA #REQUIRED
	offset CDATA #REQUIRED
	size CDATA #REQUIRED>
<!ELEMENT referencePeriodicTC EMPTY>
<!ATTLIST referencePeriodicTC
	idRef CDATA #REQUIRED
	level CDATA #REQUIRED
	fieldRef CDATA #REQUIRED
	offset CDATA #REQUIRED
	size CDATA #REQUIRED>
<!ELEMENT referenceSpecialPacket EMPTY>
<!ATTLIST referenceSpecialPacket
	idRef CDATA #REQUIRED
	level CDATA #REQUIRED
	fieldRef CDATA #REQUIRED
	offset CDATA #REQUIRED
	size CDATA #REQUIRED>

<!ELEMENT plot (GVFiltered | GVPeriodic)+>
<!ATTLIST plot
	name CDATA #REQUIRED>
<!ELEMENT alarmMsg (GVFiltered | GVPeriodic)+>
<!ATTLIST alarmMsg
	name CDATA #REQUIRED
	type (alarm1 | alarm2 | alarm3) #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT modify (GVFiltered | GVPeriodic)+>
<!ATTLIST modify
	name CDATA #REQUIRED
	type (increment | increment1wrap) #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT alarmVal (GVFiltered | GVPeriodic)+>
<!ATTLIST alarmVal
	name CDATA #REQUIRED
	type (alarm1) #REQUIRED>

<!ELEMENT GVFiltered EMPTY>
<!ATTLIST GVFiltered
	GlobalVarRef CDATA #REQUIRED
	filter CDATA #REQUIRED>
<!ELEMENT GVPeriodic EMPTY>
<!ATTLIST GVPeriodic
	GlobalVarRef CDATA #REQUIRED
	period_value CDATA #REQUIRED
	period_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT TestCase EMPTY>
<!ATTLIST TestCase
	name CDATA #REQUIRED
	procedure CDATA #REQUIRED
	req CDATA #IMPLIED
	reqAction CDATA #IMPLIED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/gss_config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE gss_config SYSTEM "DTDs/gss_config.dtd">

<gss_config>
<gss_options>
	<gss_info test_campaign="demo" version="3.1.6.6" date="2025/04/02" version_control_url="URL"/>
	<gss_info_print mainLog="enabled" portLogs="enabled" rawLog="enabled" />
	<phy_header_print mainLog="disabled" portLogs="disabled" rawLog="disabled" gssTabs="disabled" />
	<discardErrorFlags txErrors="disabled" notExpectedPackets="disabled" filtersKo="disabled" validTimesKo="enabled" />
</gss_options>
	
<Protocols>
	<Protocol id="0" name="CCSDS" typeLevel="1">
		<type name="ServiceType" offset="7" />
		<subtype name="ServiceSubtype" offset="8" />
	</Protocol>
</Protocols>

<Interfaces ProtocolPacketsFile="GSS_Interfaces/ProtocolPackets.xml">
	<MainInterface id="0" name="UART" ifType="uart" ifConfig="GSS_Interfaces/uart/uart_beef_port3.xml" ioType="in_out" protocolID="0">
		<LevelInOut id="0" name="CCSDS">
			<TMformat				file="TM_Formats/Level0/ccsds_pus_v2_tm_format.xml" />
			<TCformat				file="TC_Formats/Level0/ccsds_pus_v2_tc_format.xml" />
			<inputFilter			file="TM_Filters/Level0/asw_ccsds_pus_v2_tm_filter.xml" />
		</LevelInOut>
		
		<LevelInOut id="1" name="ASW_PUS">
			<TMformat 				file="TM_Formats/Level1/asw_pus_v2_tm_format.xml" />
			<TCformat 				file="TC_Formats/Level1/asw_pus_v2_tc_format.xml" />
			<inputFilter 			file="TM_Filters/Level1/asw_pus_v2_tm_filter.xml" />
			<export_to_prev_Level 	file="TC_Formats/Lv1_To_Lv0/asw_pus_v2_tc_to_ccsds_pus_v2_tc.xml" />
			<import_from_prev_Level	file="TM_Formats/Lv1_From_Lv0/asw_pus_v2_tm_from_ccsds_pus_v2_tm.xml" />
		</LevelInOut>
	</MainInterface>
</Interfaces>

<SpecialPackets>
	<SpecialPacket status="enabled" name="3.25 SID0" id="0" ifRef="0" levels="3" levelRef="1">
		<inputFilter			file="TM_Filters/Level1/st03/asw_pus_v2_tm_3_25_filter.xml" />
		<UpperLevels>
			<UpperLevel level="2">
				<TMformat			file="TM_Formats/Level2/st03/asw_pus_v2_tm_3_25_sid0_format.xml" />
				<inputFilter		file="TM_Filters/Level2/st03/asw_pus_v2_tm_3_25_sid0_filter.xml" />
				<import_from_prev_Level	file="TM_Formats/Lv2_From_Lv1/asw_pus_v2_tm_X_X_from_asw_pus_v2_tm.xml" />
			</UpperLevel>
		</UpperLevels>
		<printingData printStatus="disabled">
			<structuredData levelRef="2" firstField="1" />			
		</printingData>
		<period					min_value="9900" min_unit="miliseconds" max_value="10100" max_unit="miliseconds"/>
	</SpecialPacket>
</SpecialPackets>

<Tests ProtocolPacketsFile="GSS_Interfaces/ProtocolPackets.xml" >

	<TestCase name="TP_0010_ASW_PUS_TC_17_1_ARE_YOU_ALIVE" 							
		procedure="FT_PROCS/st17/tp_0010_asw_pus_tc_17_1_are_you_alive.xml"/>

	<TestCase name="TP_0020_ASW_PUS_TC_REJECT_INVALID_SUBTYPE"
		procedure="FT_PROCS/st17/tp_0020_asw_pus_tc_reject_invalid_subtype.xml"/>

	<TestCase name="TP_0030_ASW_PUS_TC_REJECT_INVALID_CRC" 							
		procedure="FT_PROCS/st17/tp_0030_asw_pus_tc_reject_invalid_crc.xml"/>

	<TestCase name="TP_0040_ASW_PUS_TC_3_31_SET_HK_PERIOD_SID_0_TO_0x05" 
		procedure="FT_PROCS/st03/tp_0040_asw_pus_tc_3_31_set_hk_period_sid_0_to_0x05.xml"/>

	<TestCase name="TP_0050_ASW_PUS_TC_3_6_TC_3_5_DISABLE_ENABLE_SID_REPORT" 
		procedure="FT_PROCS/st03/tp_0050_asw_pus_tc_3_6_tc_3_5_disable_enable_sid_report.xml"/>

	<TestCase name="TP_0060_ASW_PUS_TC_3_31_REJECT_INVALID_SID" 
		procedure="FT_PROCS/st03/tp_0060_asw_pus_tc_3_31_reject_invalid_sid.xml"/>

	<TestCase name="TP_0070_ASW_PUS_TC_3_31_REJECT_INVALID_N" 
		procedure="FT_PROCS/st03/tp_0070_asw_pus_tc_3_31_reject_invalid_N.xml"/>

	<TestCase name="TP_0080_ASW_PUS_TC_20_3_TC_20_1_SET_PID_10_TO_99" 							
		procedure="FT_PROCS/st20/tp_0080_asw_pus_tc_20_3_tc_20_1_set_pid_10_to_99.xml"/>

	<TestCase name="TP_0090_ASW_PUS_TC_20_1_INVALID_PID" 						
		procedure="FT_PROCS/st20/tp_0090_asw_pus_tc_20_1_invalid_pid.xml"/>
		
	<TestCase name="TP_0100_ASW_PUS_TC_20_3_INVALID_PID" 						
		procedure="FT_PROCS/st20/tp_0100_asw_pus_tc_20_3_invalid_pid.xml"/>

	<TestCase name="TP_0110_ASW_PUS_TC_12_5_ADD_MON_DEF_PID_10" 						
		procedure="FT_PROCS/st12/tp_0110_asw_pus_tc_12_5_add_mon_def_pid_10.xml"/>

	<TestCase name="TP_0120_ASW_PUS_SERV_4_PARAM_STATS_REPORTING" 						
		procedure="FT_PROCS/st04/tp_0120_asw_pus_serv_4_param_stats_reporting.xml"/>

	<TestCase name="TP_0130_ASW_PUS_TC_2_1_ONOFF_DEV_ADDRESS_0x60000001" 
		procedure="FT_PROCS/st02/tp_0130_asw_pus_tc_2_1_onoff_dev_address_0x60000001.xml"/>

	<TestCase name="TP_0140_ASW_PUS_TC_6_5_READ_BYTES_FROM_0x40001000_TO_0x4000103F" 
		procedure="FT_PROCS/st06/tp_0140_asw_pus_tc_6_5_read_bytes_from_0x40001000_to_0x4000103F.xml"/>

	<TestCase name="TP_0150_ASW_PUS_TC_6_2_WRITE_BYTES_TO_0x41020080" 
		procedure="FT_PROCS/st06/tp_0150_asw_pus_tc_6_2_write_bytes_to_0x41020080.xml"/>

	<TestCase name="TP_0160_ASW_PUS_TC_6_9_CHECKSUM_FROM_0x40000090_TO_0x400000BF" 
		procedure="FT_PROCS/st06/tp_0160_asw_pus_tc_6_9_checksum_from_0x40000090_to_0x400000BF.xml"/>

	<TestCase name="TP_0170_ASW_PUS_TC_6_5_REJECT_READ_BYTES_FROM_INVALID_MEMORY_ID" 
		procedure="FT_PROCS/st06/tp_0170_asw_pus_tc_6_5_reject_read_bytes_from_invalid_memory_id.xml"/>
	
	<TestCase name="TP_0180_ASW_PUS_TC_6_2_REJECT_WRITE_BYTES_TO_READ_ONLY_MEMORY" 
		procedure="FT_PROCS/st06/tp_0180_asw_pus_tc_6_2_reject_write_bytes_to_read_only_memory.xml"/>

	<TestCase name="TP_0190_ASW_PUS_TC_9_129_SET_OBT" 
		procedure="FT_PROCS/st09/tp_0190_asw_pus_tc_9_129_set_obt.xml"/>

	<TestCase name="TP_0200_ASW_PUS_SERV_19_EVENT_ACTION" 
		procedure="FT_PROCS/st19/tp_0200_asw_pus_serv_19_event_action.xml"/>
	
	<!-- TestCase name="tp_0070_asw_pus_tc_128_1_reboot" 						
			procedure="FT_PROCS/st128/tp_0070_asw_pus_tc_128_1_reboot.xml"/ !-->


</Tests>
</gss_config>
