=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/test_proc.dtd
<!ELEMENT test_proc (step+)>
<!ATTLIST test_proc
	name CDATA #REQUIRED>

<!ELEMENT step (inputs, outputs?, specialPackets?, concurrent_steps?)>
<!ATTLIST step
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	prev_step_idref CDATA #REQUIRED
	output_idref_from_prev_step CDATA #REQUIRED
	mode (continuous | manual | concurrent) #REQUIRED
	replays CDATA #IMPLIED>
<!ELEMENT specialPackets (enable | disable | enable_print | disable_print)*>
<!ELEMENT enable EMPTY>
<!ATTLIST enable
	id CDATA #REQUIRED>
<!ELEMENT disable EMPTY>
<!ATTLIST disable
	id CDATA #REQUIRED>
<!ELEMENT enable_print EMPTY>
<!ATTLIST enable_print
	id CDATA #REQUIRED>
<!ELEMENT disable_print EMPTY>
<!ATTLIST disable_print
	id CDATA #REQUIRED>
<!ELEMENT concurrent_steps (nextStep, concurrent_step*)>
<!ELEMENT nextStep EMPTY>
<!ATTLIST nextStep
	id CDATA #REQUIRED
	isConcurrent (yes | no) #REQUIRED>
<!ELEMENT concurrent_step EMPTY>
<!ATTLIST concurrent_step
	id CDATA #REQUIRED>

<!-- inputs -->
<!ELEMENT inputs ((input_level_3 | input_level_2 | input_level_1 | input_level_0)*)>

<!ELEMENT input_level_3 (level3, app_to_level3, level2, level3_to_level2, level1, level2_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_3
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED	
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_2 (level2, app_to_level2, level1, level2_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_2
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_1 (level1, app_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_1
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_0 (level0, app_to_level0)>
<!ATTLIST input_level_0
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT app_to_level3 EMPTY>
<!ATTLIST app_to_level3 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level2 EMPTY>
<!ATTLIST app_to_level2 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level1 EMPTY>
<!ATTLIST app_to_level1 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level0 EMPTY>
<!ATTLIST app_to_level0 
	export CDATA #REQUIRED>

<!ELEMENT level3_to_level2 EMPTY>
<!ATTLIST level3_to_level2
	export CDATA #REQUIRED>
<!ELEMENT level2_to_level1 EMPTY>
<!ATTLIST level2_to_level1
	export CDATA #REQUIRED>
<!ELEMENT level1_to_level0 EMPTY>
<!ATTLIST level1_to_level0
	export CDATA #REQUIRED>

<!-- outputs -->
<!ELEMENT outputs ((output_level_3 | output_level_2 | output_level_1 | output_level_0)*)>
<!ATTLIST outputs 
	checkmode (all | allunsorted | any) #REQUIRED
	valid_time_interval_value CDATA #REQUIRED
	valid_time_interval_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT output_level_3 (level3, level3_filter, level3_from_level2, level2, level2_filter, level1, level2_from_level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_3
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_2 (level2, level2_filter, level1, level2_from_level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_2
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_1 (level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_1
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_0 (level0, level0_filter)>
<!ATTLIST output_level_0
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>

<!ELEMENT level3_filter EMPTY>
<!ATTLIST level3_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level2_filter EMPTY>
<!ATTLIST level2_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level1_filter EMPTY>
<!ATTLIST level1_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level0_filter EMPTY>
<!ATTLIST level0_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>

<!ELEMENT level3_from_level2 EMPTY>
<!ATTLIST level3_from_level2
	import CDATA #REQUIRED>
<!ELEMENT level2_from_level1 EMPTY>
<!ATTLIST level2_from_level1
	import CDATA #REQUIRED>
<!ELEMENT level1_from_level0 EMPTY>
<!ATTLIST level1_from_level0
	import CDATA #REQUIRED>

<!-- inputs and outputs -->
<!ELEMENT level3 EMPTY>
<!ATTLIST level3
	format CDATA #REQUIRED>
<!ELEMENT level2 EMPTY>
<!ATTLIST level2
	format CDATA #REQUIRED>
<!ELEMENT level1 EMPTY>
<!ATTLIST level1
	format CDATA #REQUIRED>
<!ELEMENT level0 EMPTY>
<!ATTLIST level0
	format CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st06/tp_0091_asw_pus_tc_6_2_write_bytes_to_0x41020080.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<test_proc name="tp_0091_asw_pus_tc_6_2_write_bytes_to_0x41020080">
	<step name="6_2_write_bytes_to_0x41020080" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			
			<input_level_2 name="tc_6_2" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st06/asw_pus_tc_6_2_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_6_2/tc_6_2_write_bytes_to_0x41020080.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st06/asw_pus_tc_6_2_to_asw_pus_v2_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="2000" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st06/tp_0140_asw_pus_tc_6_5_read_bytes_from_0x40001000_to_0x4000103F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<!--

ID: TP_0140_ASW_PUS_TC_6_5_READ_BYTES_FROM_0x40001000_TO_0x4000103F
Description:

The test checks that telecommand TC(6,5) to read 64 bytes from memory address
0x40001000 to 0x4000103F is executed correctly and the TM (6,6) with the
expected data is received.

-->

<test_proc name="TP_0140_ASW_PUS_TC_6_5_READ_BYTES_FROM_0x40001000_TO_0x4000103F">
	<step name="tc_6_5_read_bytes_from_0x40001000_to_0x4000103F" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			
			<input_level_2 name="tc_6_5" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st06/asw_pus_tc_6_5_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_6_5/tc_6_5_read_bytes_from_0x40001000_to_0x4000103F.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st06/asw_pus_tc_6_5_to_asw_pus_v2_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="2000" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_6_6_read_bytes" id="1" ifRef="0">
				<level2 format="TM_Formats/Level2/st06/asw_pus_tm_6_6_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st06/asw_pus_tm_6_6_read_from_0x40001000_to_0x4000103F_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st06/asw_pus_tm_6_6_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st06/asw_pus_v2_tm_6_6_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st17/tp_0011_asw_pus_tc_17_3_ob_connection_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<test_proc name="tp_0011_asw_pus_tc_17_3_ob_connection_test">
	<step name="Send 17_3" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_1 name="tc_17_3" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st17/asw_pus_tc_17_3_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_17_3/tc_17_3_ob_connection_test_apid_90.xml"/>
				<level1 format="DEFAULT"/>
				<app_to_level1 export="TC_Formats/Lv2_To_Lv1/st17/asw_pus_tc_17_3_to_asw_pus_v2_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_1>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_2 name="tm_1_2" id="0" ifRef="0">
				<level2 format="TM_Formats/Level2/st01/asw_pus_v2_tm_1_2_error_6_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st01/asw_pus_tm_1_2_error_6_subtype_3_filter.xml"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st01/asw_pus_tm_1_2_from_asw_pus_v2_tm.xml"/>
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st04/tp_0120_asw_pus_serv_4_param_stats_reporting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<!--

ID: TP_0120_ASW_PUS_SERV_4_PARAM_STATS_REPORTING
Description:

The test checks that parameter statistics can be defined for Parameters 1 and 3
using TC(4,6), retrieved using TC(4,1), and that Parameter 3 statistics can be
deleted using TC(4,7), verifying the complete parameter statistics reporting
functionality. 

-->

<test_proc name="TP_0120_ASW_PUS_SERV_4_PARAM_STATS_REPORTING">
	<step name="tc_4_6" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_4_6" ifRef="0" delay_value="100" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st04/asw_pus_tc_4_6_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_4_6/tc_4_6_define_stats_PID_1.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st04/asw_pus_tc_4_6_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_4_6" id="1" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_4_6" ifRef="0" delay_value="800" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st04/asw_pus_tc_4_6_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_4_6/tc_4_6_define_stats_PID_3.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st04/asw_pus_tc_4_6_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_4_1" id="2" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_1 name="tc_4_1" ifRef="0" delay_value="1400" delay_unit="miliseconds">
				<level1 format="DEFAULT"/>
				<app_to_level1 export="TC_Formats/Lv2_To_Lv1/st04/asw_pus_tc_4_1_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_1>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_4_2_stadistics_PID_1" id="1" ifRef="0">
				<level2 format="TM_Formats/Level2/st04/asw_pus_tm_4_2_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st04/asw_pus_tm_4_2_PID_1_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st04/asw_pus_tm_4_2_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st04/asw_pus_v2_tm_4_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_2 name="tm_4_2_stadistics_PID_3" id="2" ifRef="0">
				<level2 format="TM_Formats/Level2/st04/asw_pus_tm_4_2_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st04/asw_pus_tm_4_2_PID_3_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st04/asw_pus_tm_4_2_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st04/asw_pus_v2_tm_4_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_1 name="tm_1_7" id="3" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_4_7" id="3" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_4_7" ifRef="0" delay_value="2000" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st04/asw_pus_tc_4_7_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_4_7/tc_4_7_delete_stats_PID_3.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st04/asw_pus_tc_4_7_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="5000" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_4_1" id="4" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_1 name="tc_4_1" ifRef="0" delay_value="5000" delay_unit="miliseconds">
				<level1 format="DEFAULT"/>
				<app_to_level1 export="TC_Formats/Lv2_To_Lv1/st04/asw_pus_tc_4_1_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_1>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_4_2_stadistics_PID_1" id="1" ifRef="0">
				<level2 format="TM_Formats/Level2/st04/asw_pus_tm_4_2_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st04/asw_pus_tm_4_2_PID_1_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st04/asw_pus_tm_4_2_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st04/asw_pus_v2_tm_4_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st20/tp_0040_asw_pus_tc_20_1_get_pid10_equal_99.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../DTDs/test_proc.dtd">

<test_proc name="tp_0002_asw_pus_tc_20_01_get_pid10_equal_99">
	<step name="20_1_get_pid10_equal_99" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_20_1" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st20/asw_pus_tc_20_1_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_20_1/tc_20_1_get_pid10.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st20/asw_pus_tc_20_1_to_asw_pus_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_20_2_pid10_equal_99" id="1" ifRef="0">
				<level2 format="TM_Formats/Level2/st20/asw_pus_tm_20_2_uint32_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st20/asw_pus_tm_20_2_pid10_uint32_equal_99_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st20/asw_pus_tm_20_2_uint32_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st20/asw_pus_v2_tm_20_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>
