=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/test_proc.dtd
<!ELEMENT test_proc (step+)>
<!ATTLIST test_proc
	name CDATA #REQUIRED>

<!ELEMENT step (inputs, outputs?, specialPackets?, concurrent_steps?)>
<!ATTLIST step
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	prev_step_idref CDATA #REQUIRED
	output_idref_from_prev_step CDATA #REQUIRED
	mode (continuous | manual | concurrent) #REQUIRED
	replays CDATA #IMPLIED>
<!ELEMENT specialPackets (enable | disable | enable_print | disable_print)*>
<!ELEMENT enable EMPTY>
<!ATTLIST enable
	id CDATA #REQUIRED>
<!ELEMENT disable EMPTY>
<!ATTLIST disable
	id CDATA #REQUIRED>
<!ELEMENT enable_print EMPTY>
<!ATTLIST enable_print
	id CDATA #REQUIRED>
<!ELEMENT disable_print EMPTY>
<!ATTLIST disable_print
	id CDATA #REQUIRED>
<!ELEMENT concurrent_steps (nextStep, concurrent_step*)>
<!ELEMENT nextStep EMPTY>
<!ATTLIST nextStep
	id CDATA #REQUIRED
	isConcurrent (yes | no) #REQUIRED>
<!ELEMENT concurrent_step EMPTY>
<!ATTLIST concurrent_step
	id CDATA #REQUIRED>

<!-- inputs -->
<!ELEMENT inputs ((input_level_3 | input_level_2 | input_level_1 | input_level_0)*)>

<!ELEMENT input_level_3 (level3, app_to_level3, level2, level3_to_level2, level1, level2_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_3
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED	
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_2 (level2, app_to_level2, level1, level2_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_2
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_1 (level1, app_to_level1, level0, level1_to_level0)>
<!ATTLIST input_level_1
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>
<!ELEMENT input_level_0 (level0, app_to_level0)>
<!ATTLIST input_level_0
	name CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	delay_value CDATA #REQUIRED
	delay_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT app_to_level3 EMPTY>
<!ATTLIST app_to_level3 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level2 EMPTY>
<!ATTLIST app_to_level2 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level1 EMPTY>
<!ATTLIST app_to_level1 
	export CDATA #REQUIRED>
<!ELEMENT app_to_level0 EMPTY>
<!ATTLIST app_to_level0 
	export CDATA #REQUIRED>

<!ELEMENT level3_to_level2 EMPTY>
<!ATTLIST level3_to_level2
	export CDATA #REQUIRED>
<!ELEMENT level2_to_level1 EMPTY>
<!ATTLIST level2_to_level1
	export CDATA #REQUIRED>
<!ELEMENT level1_to_level0 EMPTY>
<!ATTLIST level1_to_level0
	export CDATA #REQUIRED>

<!-- outputs -->
<!ELEMENT outputs ((output_level_3 | output_level_2 | output_level_1 | output_level_0)*)>
<!ATTLIST outputs 
	checkmode (all | allunsorted | any) #REQUIRED
	valid_time_interval_value CDATA #REQUIRED
	valid_time_interval_unit (miliseconds | seconds) #REQUIRED>

<!ELEMENT output_level_3 (level3, level3_filter, level3_from_level2, level2, level2_filter, level1, level2_from_level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_3
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_2 (level2, level2_filter, level1, level2_from_level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_2
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_1 (level1, level1_filter, level0, level1_from_level0, level0_filter)>
<!ATTLIST output_level_1
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>
<!ELEMENT output_level_0 (level0, level0_filter)>
<!ATTLIST output_level_0
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	ifRef CDATA #REQUIRED
	optional CDATA #IMPLIED>

<!ELEMENT level3_filter EMPTY>
<!ATTLIST level3_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level2_filter EMPTY>
<!ATTLIST level2_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level1_filter EMPTY>
<!ATTLIST level1_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>
<!ELEMENT level0_filter EMPTY>
<!ATTLIST level0_filter
	apply_def_filter (yes | no) #REQUIRED
	extra_filter CDATA #REQUIRED>

<!ELEMENT level3_from_level2 EMPTY>
<!ATTLIST level3_from_level2
	import CDATA #REQUIRED>
<!ELEMENT level2_from_level1 EMPTY>
<!ATTLIST level2_from_level1
	import CDATA #REQUIRED>
<!ELEMENT level1_from_level0 EMPTY>
<!ATTLIST level1_from_level0
	import CDATA #REQUIRED>

<!-- inputs and outputs -->
<!ELEMENT level3 EMPTY>
<!ATTLIST level3
	format CDATA #REQUIRED>
<!ELEMENT level2 EMPTY>
<!ATTLIST level2
	format CDATA #REQUIRED>
<!ELEMENT level1 EMPTY>
<!ATTLIST level1
	format CDATA #REQUIRED>
<!ELEMENT level0 EMPTY>
<!ATTLIST level0
	format CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st12/tp_0050_pus_tc_12_5_add_mon_def_pid10_to_01_0x4000_0x10_0x4001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../DTDs/test_proc.dtd">

<test_proc name="tp_0050_pus_tc_12_5_add_pmonid0_pid10_low_limit_value_01_rid_0x4000_high_limit_value_10_rid_0x4001">
	<!-- step name="20_3_set_pid10_to_5" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_20_3" ifRef="0" delay_value="200" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st20/asw_pus_tc_20_3_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_20_3/tc_20_3_set_pid10_to_99.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st20/asw_pus_tc_20_3_uint32_to_asw_pus_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">		
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step !-->
	<step name="12_5_add_pmonid0_pid10_to_0x01_0x4000_10_0x4001" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>			
			<input_level_2 name="tc_12_5" ifRef="0" delay_value="800" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st12/asw_pus_tc_12_5_limits_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_12_05/tc_12_5_set_pmonid_0_to_pid10_to_0x01_0x4000_0x0A_0x4001.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st12/asw_pus_tc_12_5_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="12_1_enable_pmon_id_0" 	id="1" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>			
			<input_level_2 name="tc_12_1" ifRef="0" delay_value="1400" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st12/asw_pus_tc_12_1_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_12_01/tc_12_1_enable_pmonid_0.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st12/asw_pus_tc_12_1_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<!-- step name="20_3_set_pid10_to_99_force_0x4001_event" id="3" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_20_3" ifRef="0" delay_value="2000" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st20/asw_pus_tc_20_3_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_20_3/tc_20_3_set_pid10_to_99.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st20/asw_pus_tc_20_3_uint32_to_asw_pus_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="5000" valid_time_interval_unit="miliseconds">		
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_5_4_ev_id_equal_0x4001" id="2" ifRef="0">
				<level2 format="TM_Formats/Level2/st05/asw_pus_v2_tm_5_4_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st05/asw_pus_tm_5_4_ev_id_equal_0x4001_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st05/asw_pus_tm_5_4_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st05/asw_pus_v2_tm_5_4_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>


		</outputs>			
	</step !-->
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st12/tp_0110_asw_pus_tc_12_5_add_mon_def_pid_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../DTDs/test_proc.dtd">

<!--

ID: TP_0110_ASW_PUS_TC_12_5_ADD_MON_DEF_PID_10
Description:

The test checks that a monitoring definition for Parameter 10 is added using
TC(12,5), enabled using TC(12,1), and that the monitoring system correctly
detects limit violations and generates the appropriate events.

-->


<test_proc name="TP_0110_ASW_PUS_TC_12_5_ADD_MON_DEF_PID_10">
	<step name="tc_20_3_set_pid_10_to_5" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_20_3" ifRef="0" delay_value="100" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st20/asw_pus_tc_20_3_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_20_3/tc_20_3_set_pid_10_to_99.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st20/asw_pus_tc_20_3_uint32_to_asw_pus_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">		
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_12_5_add_pmonid0_pid_10_to_0x01_0x4000_10_0x4001" id="1" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>			
			<input_level_2 name="tc_12_5" ifRef="0" delay_value="800" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st12/asw_pus_tc_12_5_limits_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_12_05/tc_12_5_set_pmonid_0_to_pid_10_to_0x01_0x4000_0x0A_0x4001.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st12/asw_pus_tc_12_5_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_12_1_enable_pmon_id_0" 	id="2" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>			
			<input_level_2 name="tc_12_1" ifRef="0" delay_value="1400" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st12/asw_pus_tc_12_1_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_12_01/tc_12_1_enable_pmonid_0.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st12/asw_pus_tc_12_1_to_asw_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
	<step name="tc_20_3_set_pid_10_to_99_force_0x4001_event" id="3" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_20_3" ifRef="0" delay_value="2000" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st20/asw_pus_tc_20_3_uint32_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_20_3/tc_20_3_set_pid_10_to_99.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st20/asw_pus_tc_20_3_uint32_to_asw_pus_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="5000" valid_time_interval_unit="miliseconds">		
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_2 name="tm_12_12_monitoring_transition" id="2" ifRef="0">
				<level2 format="TM_Formats/Level2/st12/asw_pus_tm_12_12_limits_monitoring_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st12/asw_pus_tm_12_12_limits_monitoring_filter_PMONID_0_PID_10.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st12/asw_pus_tm_12_12_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st12/asw_pus_v2_tm_12_12_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
			<output_level_2 name="tm_5_4_ev_id_equal_0x4001" id="3" ifRef="0">
				<level2 format="TM_Formats/Level2/st05/asw_pus_v2_tm_5_4_format.xml"/>
				<level2_filter apply_def_filter="no" extra_filter="TM_Filters/Level2/st05/asw_pus_tm_5_4_ev_id_equal_0x4001_filter.xml"/>
				<level1 format="DEFAULT"/>
 				<level2_from_level1 import="TM_Formats/Lv2_From_Lv1/st05/asw_pus_tm_5_4_from_asw_pus_v2_tm.xml"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st05/asw_pus_v2_tm_5_4_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_2>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st17/tp_0010_asw_pus_tc_17_1_are_you_alive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<test_proc name="tp_0001_asw_pus_tc_17_1_are_you_alive">
	<step name="Send 17_1" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_1 name="tc_17_1" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level1 format="DEFAULT"/>
				<app_to_level1 export="TC_Formats/Lv2_To_Lv1/st17/asw_pus_tc_17_1_to_asw_pus_v2_tc_ack_0b1001.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_1>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_17_1" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st17/asw_pus_v2_tm_17_2_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/tp_0060_pus_tc_12_1_disable_pmonid_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../DTDs/test_proc.dtd">

<test_proc name="tp_0060_pus_tc_12_02_disable_pmonid_0">
	<step name="12_02_disable_pmonid_0" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			<input_level_2 name="tc_12_1" ifRef="0" delay_value="120" delay_unit="miliseconds">
				<level2 format="GSS_Interfaces/uart/TC_Formats/Level2/epd_pus_tc_12_2_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_12_02/tc_12_2_disable_pmonid_0.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="GSS_Interfaces/uart/TC_Formats/Lv2_To_Lv1/epd_pus_tc_12_2_to_epd_pus_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="GSS_Interfaces/uart/TM_Filters/Level1/epd_pus_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="GSS_Interfaces/uart/TM_Filters/Level1/epd_pus_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/FT_PROCS/st03/tp_0050_asw_pus_tc_3_6_tc_3_5_disable_enable_sid_report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test_proc SYSTEM "../../DTDs/test_proc.dtd">

<!--

ID: TP_0050_ASW_PUS_TC_3_6_TC_3_5_DISABLE_ENABLE_SID_REPORT
Description:

The test checks that telecommand TC(3,6) to disable SID report and TC(3,5) to
enable SID report are executed correctly and the appropriate TM responses are
received.

-->

<test_proc name="TP_0050_ASW_PUS_TC_3_6_TC_3_5_DISABLE_ENABLE_SID_REPORT">
	<step name="tc_3_6_disable_sid_0" id="0" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			
			<input_level_2 name="tc_3_6" ifRef="0" delay_value="100" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st03/asw_pus_tc_3_5_tc_3_6_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_3_6/tc_3_6_disable_hk_period_sid0.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st03/asw_pus_tc_3_6_to_asw_pus_v2_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_3" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_3_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
    <step name="tc_3_5_enable_sid_0" id="1" prev_step_idref="NULL" output_idref_from_prev_step="NULL" mode="continuous">
		<inputs>
			
			<input_level_2 name="tc_3_5" ifRef="0" delay_value="24000" delay_unit="miliseconds">
				<level2 format="TC_Formats/Level2/st03/asw_pus_tc_3_5_tc_3_6_format.xml"/>
				<app_to_level2 export="STEPS_XML/INPUTS/tc_3_5/tc_3_5_enable_hk_period_sid0.xml"/>
				<level1 format="DEFAULT"/>
				<level2_to_level1 export="TC_Formats/Lv2_To_Lv1/st03/asw_pus_tc_3_5_to_asw_pus_v2_tc_ack.xml"/>
				<level0 format="DEFAULT"/>
				<level1_to_level0 export="DEFAULT"/>
			</input_level_2>
		
		</inputs>
		<outputs checkmode="all" valid_time_interval_value="500" valid_time_interval_unit="miliseconds">
			<output_level_1 name="tm_1_1" id="0" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_1_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_3" id="1" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_3_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
			<output_level_1 name="tm_1_7" id="2" ifRef="0">
				<level1 format="DEFAULT"/>
				<level1_filter apply_def_filter="yes" extra_filter="TM_Filters/Level1/st01/asw_pus_v2_tm_1_7_filter.xml"/>
				<level0 format="DEFAULT"/>
				<level1_from_level0 import="DEFAULT"/>
				<level0_filter apply_def_filter="yes" extra_filter="NULL"/>
			</output_level_1>
		</outputs>			
	</step>
</test_proc>
