=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/tm_tc_format.dtd
<!ELEMENT tm_tc_format ((CSField | CSFormulaField | VSField | FDICField | VRFieldSize | AField | AIField)*)>
<!ATTLIST tm_tc_format
	protocol CDATA #REQUIRED
	type (TM | TC) #REQUIRED>

<!ELEMENT CSField (size, globalOffset)>
<!ATTLIST CSField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT size EMPTY>
<!ATTLIST size
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT globalOffset EMPTY>
<!ATTLIST globalOffset
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT CSFormulaField (size, globalOffset, formula)>
<!ATTLIST CSFormulaField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT formula EMPTY>
<!ATTLIST formula
	slope CDATA #REQUIRED
	intercept CDATA #REQUIRED>

<!ELEMENT VSField (constSize, variableSize, maxSize, globalOffset)>
<!ATTLIST VSField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT constSize EMPTY>
<!ATTLIST constSize
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT variableSize EMPTY>
<!ATTLIST variableSize
	fidRef NMTOKEN #REQUIRED
	unit (bytes | bits | halfword | string10 | string17 | string69) #REQUIRED
	power (2 | 2_with_0) #IMPLIED>
	
<!ELEMENT maxSize EMPTY>
<!ATTLIST maxSize
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT VRFieldSize EMPTY>
<!ATTLIST VRFieldSize
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED>

<!ELEMENT FDICField (size, floatingOffset, sortedFieldsToCheck)>
<!ATTLIST FDICField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	checkType (crc16 | checksum16) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT floatingOffset EMPTY>
<!ATTLIST floatingOffset
	fidRef NMTOKEN #REQUIRED>

<!ELEMENT sortedFieldsToCheck (fieldToCheck+)>
<!ELEMENT fieldToCheck EMPTY>
<!ATTLIST fieldToCheck
	fidRef NMTOKEN #REQUIRED>

<!ELEMENT AField (arrayDimension, size, globalOffset)>
<!ATTLIST AField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT arrayDimension EMPTY>
<!ATTLIST arrayDimension
	fidRef NMTOKEN #REQUIRED
	maxItems CDATA #REQUIRED>

<!ELEMENT AIField (arrayRef, size, localOffset)>
<!ATTLIST AIField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT arrayRef EMPTY>
<!ATTLIST arrayRef
	fidRef NMTOKEN #REQUIRED>
	
<!ELEMENT localOffset EMPTY>
<!ATTLIST localOffset
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/st09/asw_pus_tc_9_129_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="TC_9.129" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="6" bits="0" />				<!-- size in bits = 24 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="NextOBTSeconds" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="0" name="NextOBTFinetime" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="4" bits="0" />		<!-- offset in bits = 1x8 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level1/asw_pus_v2_tc_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="PUS" type="TC">
	<CSField fid="0" pfid="0" name="SecondaryHeader" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="5" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="CCSDSSecondaryHeaderFlag" type="flag" byteOrder="na" firstBit="MSB">
		<size bytes="0" bits="1" />				<!-- size in bits = 1 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="2" pfid="0" name="PUSVersion" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="3" />				<!-- size in bits = 3 -->
		<globalOffset bytes="0" bits="1" />		<!-- offset in bits = 1 -->
	</CSField>

	<CSField fid="3" pfid="0" name="ACK" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="4" />				<!-- size in bits = 4 -->
		<globalOffset bytes="0" bits="4" />		<!-- offset in bits = 4 -->
	</CSField>

	<CSField fid="4" pfid="0" name="ServiceType" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 8 -->
	</CSField>

	<CSField fid="5" pfid="0" name="ServiceSubtype" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="6" pfid="0" name="SourceID" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="3" bits="0" />		<!-- offset in bits = 24 -->
	</CSField>

	<VSField fid="7" pfid="7" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="0" bits="0" />		<!-- const size in bits = 0 -->
		<variableSize fidRef="8" unit="bytes" /><!-- vble size = (AppDataLength x 8) bits -->
		<maxSize bytes="243" bits="0" />		<!-- max size in bits = 243 * 8 -->
		<globalOffset bytes="5" bits="0" />		<!-- offset in bits = 32 -->
	</VSField>
	
	<VRFieldSize fid="8" pfid="7" name="AppDataLength" /> <!-- in bytes -->
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/st06/asw_pus_tc_6_2_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="EPD_6.2" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="32" bits="0" />				<!-- size in bits = 64 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="MemoryID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="2" pfid="0" name="N" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 8 -->
	</CSField>

	<CSField fid="3" pfid="0" name="StartAddress" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 3x8 -->
	</CSField>

	<CSField fid="4" pfid="0" name="Length" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="6" bits="0" />		<!-- offset in bits = 3x8 -->
	</CSField>

	<VSField fid="5" pfid="0" name="DataToWrite" type="string" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="0" bits="0" />		<!-- const size in bits = 0 -->
		<variableSize fidRef="4" unit="bytes" /><!-- vble size = (DataToWriteLength x 8) bits -->
		<maxSize bytes="256" bits="0" />		<!-- max size in bits = 243 * 8 -->
		<globalOffset bytes="8" bits="0" />		<!-- offset in bits = 32 -->
	</VSField>

	<VRFieldSize fid="6" pfid="5" name="DataToWriteLength" /> <!-- in bytes -->

</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st06/asw_pus_tm_6_6_size_64_bytes_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_6.6" type="TM">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="72" bits="0" />			<!-- size in bits = 72*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="MemoryID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="0" name="N" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="3" pfid="0" name="StartAddress" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="2" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="4" pfid="0" name="Length" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="2" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="6" bits="0" /> 	<!-- offset in bits = 48 -->
	</CSField>
	<CSField fid="5" pfid="0" name="Data" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="64" bits="0" />			<!-- size in bits = 64*8 -->
        <globalOffset bytes="8" bits="0" /> 	<!-- offset in bits = 64 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st05/asw_pus_v2_tm_5_4_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_5.4" type="TM">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />			<!-- size in bits = 4*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="Ev_ID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="1" name="ErrorCode" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="2" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st04/asw_pus_tm_4_2_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_4.2" type="TM">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="35" bits="0" />			<!-- size in bits = 4*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="StartTime" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="0" name="CurrentTime" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="4" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="3" pfid="0" name="N" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="8" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="4" pfid="0" name="PID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="9" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="5" pfid="0" name="Samples" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="11" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="6" pfid="0" name="MaxValue" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="15" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="7" pfid="0" name="MaxValueOBT" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="19" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="8" pfid="0" name="MinValue" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="23" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="9" pfid="0" name="MinValueOBT" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="27" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="10" pfid="0" name="MeanValue" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="31" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/epd_pus_tc_12_5_format.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tm_tc_format SYSTEM "../../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="EPD_12_5" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="13" bits="0" />			<!-- size in bits = 104 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="PMON_ID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="2" pfid="0" name="Parameter_ID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>	

	<CSField fid="3" pfid="0" name="Monitoring_Interval" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="4" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>
		
	<CSField fid="4" pfid="0" name="Low_Limit" type="deduced" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 64 -->
		<globalOffset bytes="5" bits="0" />		<!-- offset in bits = 40 -->
	</CSField>
	
	<CSField fid="5" pfid="0" name="Low_Limit_EV_ID" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="7" bits="0" />	<!-- offset in bits = 104 -->
	</CSField>
	
	<CSField fid="6" pfid="0" name="High_Limit" type="deduced" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 64 -->
		<globalOffset bytes="9" bits="0" />	<!-- offset in bits = 120 -->
	</CSField>	
	
	<CSField fid="7" pfid="0" name="High_Limit_EV_ID" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="11" bits="0" />	<!-- offset in bits = 184 -->
	</CSField>

</tm_tc_format>
