=== termina-lang/obdh-asw-termina/assets/massiva_workspace/DTDs/tm_tc_format.dtd
<!ELEMENT tm_tc_format ((CSField | CSFormulaField | VSField | FDICField | VRFieldSize | AField | AIField)*)>
<!ATTLIST tm_tc_format
	protocol CDATA #REQUIRED
	type (TM | TC) #REQUIRED>

<!ELEMENT CSField (size, globalOffset)>
<!ATTLIST CSField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT size EMPTY>
<!ATTLIST size
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT globalOffset EMPTY>
<!ATTLIST globalOffset
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT CSFormulaField (size, globalOffset, formula)>
<!ATTLIST CSFormulaField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT formula EMPTY>
<!ATTLIST formula
	slope CDATA #REQUIRED
	intercept CDATA #REQUIRED>

<!ELEMENT VSField (constSize, variableSize, maxSize, globalOffset)>
<!ATTLIST VSField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT constSize EMPTY>
<!ATTLIST constSize
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT variableSize EMPTY>
<!ATTLIST variableSize
	fidRef NMTOKEN #REQUIRED
	unit (bytes | bits | halfword | string10 | string17 | string69) #REQUIRED
	power (2 | 2_with_0) #IMPLIED>
	
<!ELEMENT maxSize EMPTY>
<!ATTLIST maxSize
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

<!ELEMENT VRFieldSize EMPTY>
<!ATTLIST VRFieldSize
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED>

<!ELEMENT FDICField (size, floatingOffset, sortedFieldsToCheck)>
<!ATTLIST FDICField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	checkType (crc16 | checksum16) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT floatingOffset EMPTY>
<!ATTLIST floatingOffset
	fidRef NMTOKEN #REQUIRED>

<!ELEMENT sortedFieldsToCheck (fieldToCheck+)>
<!ELEMENT fieldToCheck EMPTY>
<!ATTLIST fieldToCheck
	fidRef NMTOKEN #REQUIRED>

<!ELEMENT AField (arrayDimension, size, globalOffset)>
<!ATTLIST AField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT arrayDimension EMPTY>
<!ATTLIST arrayDimension
	fidRef NMTOKEN #REQUIRED
	maxItems CDATA #REQUIRED>

<!ELEMENT AIField (arrayRef, size, localOffset)>
<!ATTLIST AIField
	fid NMTOKEN #REQUIRED
	pfid NMTOKEN #REQUIRED
	name CDATA #REQUIRED
	description CDATA #IMPLIED
	type (structured | uint | flag | enumerated | bit_vector | byte_vector | float | deduced) #REQUIRED
	byteOrder (big_endian | little_endian | na) #REQUIRED
	firstBit (MSB | LSB) #REQUIRED>

<!ELEMENT arrayRef EMPTY>
<!ATTLIST arrayRef
	fidRef NMTOKEN #REQUIRED>
	
<!ELEMENT localOffset EMPTY>
<!ATTLIST localOffset
	bytes CDATA #REQUIRED
	bits CDATA #REQUIRED>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/st20/asw_pus_tc_20_3_uint32_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="EPD_20.3" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="7" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	
	<CSField fid="1" pfid="0" name="N" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>


	<CSField fid="2" pfid="0" name="PID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 1 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="3" pfid="0" name="PIDValue" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 3 -->
		<globalOffset bytes="3" bits="0" />		<!-- offset in bits = 1 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level0/ccsds_pus_v2_tc_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="CCSDS" type="TC">
	<VSField fid="0" pfid="0" name="CCSDSPacket" type="structured" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="7" bits="0" />		<!-- const size in bits = 56 -->
		<variableSize fidRef="12" unit="bytes"/><!-- vble size = PacketLength + 7 bytes -->
		<maxSize bytes="248" bits="0" />		<!-- max size in bits = 248 * 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</VSField>

	<CSField fid="1" pfid="0" name="PacketHeader" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="6" bits="0" />				<!-- size in bits = 48 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="2" pfid="1" name="PacketID" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="3" pfid="2" name="VersionNumber" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="3" />				<!-- size in bits = 3 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="4" pfid="2" name="Type" type="flag" byteOrder="na" firstBit="MSB">
		<size bytes="0" bits="1" />				<!-- size in bits = 1 -->
		<globalOffset bytes="0" bits="3" />		<!-- offset in bits = 3 -->
	</CSField>

	<CSField fid="5" pfid="2" name="DFHFlag" type="flag" byteOrder="na" firstBit="MSB">
		<size bytes="0" bits="1" />				<!-- size in bits = 1 -->
		<globalOffset bytes="0" bits="4" />		<!-- offset in bits = 4 -->
	</CSField>

	<CSField fid="6" pfid="2" name="APID" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="11" />			<!-- size in bits = 11 -->
		<globalOffset bytes="0" bits="5" />		<!-- offset in bits = 5 -->
	</CSField>

	<CSField fid="7" pfid="6" name="PID" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="7" />				<!-- size in bits = 7 -->
		<globalOffset bytes="0" bits="5" />		<!-- offset in bits = 5 -->
	</CSField>

	<CSField fid="8" pfid="6" name="PCAT" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="4" />				<!-- size in bits = 4 -->
		<globalOffset bytes="0" bits="12" />	<!-- offset in bits = 12 -->
	</CSField>

	<CSField fid="9" pfid="1" name="PacketSequenceControl" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="10" pfid="9" name="SequenceFlag" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="2" />				<!-- size in bits = 2 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="11" pfid="9" name="SequenceCount" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="14" />			<!-- size in bits = 14 -->
		<globalOffset bytes="2" bits="2" />		<!-- offset in bits = 18 -->
	</CSField>

	<CSField fid="12" pfid="1" name="PacketLength" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="4" bits="0" />		<!-- offset in bits = 32 -->
	</CSField>

	<VSField fid="13" pfid="0" name="PacketDataField" type="structured" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="1" bits="0" />		<!-- const size in bits = 8 -->
		<variableSize fidRef="12" unit="bytes"/><!-- vble size = PacketLength + 1 bytes -->
		<maxSize bytes="250" bits="0" />		<!-- max size in bits = 250 * 8 -->
		<globalOffset bytes="6" bits="0" />		<!-- offset in bits = 48 -->
	</VSField>

	<CSField fid="14" pfid="13" name="SecondaryHeader" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="5" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="6" bits="0" />		<!-- offset in bits = 48 -->
	</CSField>

	<VSField fid="15" pfid="13" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="-6" bits="0" />		<!-- const size in bits = -40 -->
		<variableSize fidRef="12" unit="bytes"/><!-- vble size = PacketLength + 1 - 5 [SecondaryHeader] - 2 [CRC] bytes -->
		<maxSize bytes="243" bits="0" />		<!-- max size in bits = 236 * 8 -->
		<globalOffset bytes="11" bits="0" />	<!-- offset in bits = 80 -->
	</VSField>

	<!-- Floating Data Integrity Check field -->
	<FDICField fid="16" pfid="13" name="CRC" checkType="crc16" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" /> 		<!-- size in bits = 16 -->
		<floatingOffset fidRef="15" /> 		<!-- Located after "ApplicationData" -->
		<sortedFieldsToCheck>				<!-- It checks several fields: -->
			<fieldToCheck fidRef="1" />			<!-- "PacketHeader" -->	
			<fieldToCheck fidRef="14" />		<!-- "SecondaryHeader" -->	
			<fieldToCheck fidRef="15" />		<!-- "ApplicationData" -->	
		</sortedFieldsToCheck> 
	</FDICField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/st19/asw_pus_tc_19_5_format.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_19_5" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="3" bits="0" />			<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="N" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

    <CSField fid="2" pfid="0" name="EvID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st06/asw_pus_tm_6_6_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_6.6" type="TM">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="72" bits="0" />			<!-- size in bits = 72*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="MemoryID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="0" name="N" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="3" pfid="0" name="StartAddress" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="2" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="4" pfid="0" name="Length" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="2" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="6" bits="0" /> 	<!-- offset in bits = 48 -->
	</CSField>
	<VSField fid="5" pfid="0" name="ReadData" type="string" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="0" bits="0" />		<!-- const size in bits = 0 -->
		<variableSize fidRef="6" unit="bytes"/><!-- vble size = (SourceDataLength x 8) bits -->
		<maxSize bytes="256" bits="0" />		<!-- max size in bits = 4094 * 8 -->
		<globalOffset bytes="8" bits="0" />	<!-- offset in bits = 32 -->
	</VSField>

	<VRFieldSize fid="6" pfid="5" name="ReadDataLength" /> <!-- in bytes -->

</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st03/asw_pus_v2_tm_3_25_sid0_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="EPD_3.25 SID0" type="TC">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="22" bits="0" />			<!-- size in bits = 9*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="SID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSFormulaField fid="2" pfid="0" name="Current_3_3V" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 16 -->
		<formula slope="20.0/4096" intercept="-10" />
	</CSFormulaField>
	
	<CSFormulaField fid="3" pfid="0" name="Current_5V" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="6" bits="0" />		<!-- offset in bits = 32 -->
		<formula slope="20.0/4096" intercept="-10" />
	</CSFormulaField>
	
	<CSFormulaField fid="4" pfid="0" name="Volt_3_3V" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="10" bits="0" />		<!-- offset in bits = 48 -->
		<formula slope="20.0/4096" intercept="-10" />
	</CSFormulaField>

	<CSFormulaField fid="5" pfid="0" name="Volt_5V" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="14" bits="0" />		<!-- offset in bits = 48 -->
		<formula slope="20.0/4096" intercept="-10" />
	</CSFormulaField>

	<CSFormulaField fid="6" pfid="0" name="Temp" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="18" bits="0" />		<!-- offset in bits = 48 -->
		<formula slope="40.0/4096" intercept="-10" />
	</CSFormulaField>
	
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level2/st12/asw_pus_tm_12_12_limits_monitoring_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="ASW_12.12" type="TM">
	<CSField fid="0" pfid="0" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="20" bits="0" />			<!-- size in bits = 4*8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="1" pfid="0" name="counter" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="0" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="2" pfid="0" name="PMONID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="1" bits="0" /> 	<!-- offset in bits = 0 -->
	</CSField>
	<CSField fid="3" pfid="0" name="PID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="3" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
    <CSField fid="4" pfid="0" name="PMON_type" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="1" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="5" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
	<CSField fid="5" pfid="0" name="parameter_value" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="4" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="6" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
	<CSField fid="6" pfid="0" name="limit_crossed" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="4" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="10" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
	<CSField fid="7" pfid="0" name="prev_pmon_status" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="1" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="14" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
	<CSField fid="8" pfid="0" name="current_pmon_status" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="1" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="15" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
	<CSField fid="9" pfid="0" name="transition_obt" type="uint" byteOrder="big_endian" firstBit="MSB">
        <size bytes="4" bits="0" />				<!-- size in bits = 16 -->
        <globalOffset bytes="16" bits="0" /> 	<!-- offset in bits = 16 -->
	</CSField>
</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TC_Formats/Level2/st06/asw_pus_tc_6_9_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="EPD_6.9" type="TC">
	<CSField fid="0" pfid="0" name="ApplicationData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="8" bits="0" />				<!-- size in bits = 64 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="MemoryID" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="2" pfid="0" name="N" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 8 -->
	</CSField>

	<CSField fid="3" pfid="0" name="StartAddress" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 3x8 -->
	</CSField>

	<CSField fid="4" pfid="0" name="Length" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="6" bits="0" />		<!-- offset in bits = 3x8 -->
	</CSField>

</tm_tc_format>

=== termina-lang/obdh-asw-termina/assets/massiva_workspace/TM_Formats/Level1/asw_pus_v2_tm_format.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tm_tc_format SYSTEM "../../DTDs/tm_tc_format.dtd">

<tm_tc_format protocol="PUS" type="TM">
	<CSField fid="0" pfid="0" name="SecondaryHeader" type="structured" byteOrder="big_endian" firstBit="MSB">
		<size bytes="13" bits="0" />			<!-- size in bits = 32 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 0 -->
	</CSField>

	<CSField fid="1" pfid="0" name="Spare" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="1" />				<!-- size in bits = 1 -->
		<globalOffset bytes="0" bits="0" />		<!-- offset in bits = 1 -->
	</CSField>
	
	<CSField fid="2" pfid="0" name="PUSVersion" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="3" />				<!-- size in bits = 3 -->
		<globalOffset bytes="0" bits="1" />		<!-- offset in bits = 1 -->
	</CSField>
	
	<CSField fid="3" pfid="0" name="OBT_Status" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="0" bits="4" />				<!-- size in bits = 4 -->
		<globalOffset bytes="0" bits="4" />		<!-- offset in bits = 4 -->
	</CSField>

	<CSField fid="4" pfid="0" name="ServiceType" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="1" bits="0" />		<!-- offset in bits = 8 -->
	</CSField>

	<CSField fid="5" pfid="0" name="ServiceSubtype" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="1" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="2" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="6" pfid="0" name="MsgTypeCounter" type="flag" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="3" bits="0" />		<!-- offset in bits = 24 -->
	</CSField>

	<CSField fid="7" pfid="0" name="DestinationID" type="enumerated" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 8 -->
		<globalOffset bytes="5" bits="0" />		<!-- offset in bits = 16 -->
	</CSField>

	<CSField fid="8" pfid="0" name="OBT_Secs" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="4" bits="0" />				<!-- size in bits = 32 -->
		<globalOffset bytes="7" bits="0" />		<!-- offset in bytes = 7 -->
	</CSField>

	<CSField fid="9" pfid="0" name="OBT_Finetime" type="uint" byteOrder="big_endian" firstBit="MSB">
		<size bytes="2" bits="0" />				<!-- size in bits = 16 -->
		<globalOffset bytes="11" bits="0" />		<!-- offset in bytes = 11 -->
	</CSField>

	<VSField fid="10" pfid="10" name="SourceData" type="structured" byteOrder="big_endian" firstBit="MSB">
		<constSize bytes="0" bits="0" />		<!-- const size in bits = 0 -->
		<variableSize fidRef="11" unit="bytes"/><!-- vble size = (SourceDataLength x 8) bits -->
		<maxSize bytes="4085" bits="0" />		<!-- max size in bits = 4094 * 8 -->
		<globalOffset bytes="13" bits="0" />	<!-- offset in bits = 32 -->
	</VSField>

	<VRFieldSize fid="11" pfid="10" name="SourceDataLength" /> <!-- in bytes -->

</tm_tc_format>
